export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import FaqHeader from "../../components/FaqHeader/FaqHeader";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <FaqHeader isWhite />
        <div className="bg-slate-900">{children}</div>
      </body>
    </html>
  );
}
